// This file should be launched with the hyperspace-simulator to simulate a remote network.
// e.g. hyperspace-simulator peer-two.js

const { Client } = require('hyperspace')

const STATS_CORE_KEY = '(the key generated by peer-one.js)'

start()

async function start () {
  const { corestore, replicate } = new Client()
  const store = corestore()

  // Get the stats core.
  const statsCore = store.get({ key: STATS_CORE_KEY, valueEncoding: 'json' })

  await replicate(statsCore)

  // Print the last block from the stats core.
  const lastBlock = await statsCore.get(statsCore.length - 1)
  console.log(lastBlock)
}
